# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddCourse',
            new_name='Course',
        ),
        migrations.RemoveField(
            model_name='viewcourse',
            name='addcourse',
        ),
        migrations.DeleteModel(
            name='ViewCourse',
        ),
    ]
